### ISSUE TITLE
How to get the value for "repository:"

### ISSUE THREAD

**Issue by dcvtruong** [utkarshpoc/azure-vote-helm-chart#1]
How to get the value for "repository:"?
```
resources:
 repositories:
   - repository: helmrepo
     type: github
     name: utkarshpoc/azure-vote-helm-chart
     endpoint: github
```

Thanks for providing this example.
